services:
  - type: web
    name: unganaconnect
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DefaultConnection
        sync: false
      - key: AzureBlobStorage
        sync: false
