// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UnganaConnect.Data;

#nullable disable

namespace UnganaConnect.Migrations
{
    [DbContext(typeof(UnganaConnectDbContext))]
    [Migration("20260524192041_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnganaConnect.Frontend.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Agenda")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Materials")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("Participants")
                        .HasColumnType("integer");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agenda = new List<string>(),
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A hands-on workshop exploring how African CSOs can leverage ICT tools for greater community impact. Topics include digital fundraising, online collaboration, and social media strategy.",
                            Duration = "Full Day",
                            Format = "Hybrid",
                            Instructor = "Ungana-Afrika Team",
                            Level = "All Levels",
                            Location = "Johannesburg, South Africa",
                            Materials = new List<string>(),
                            MaxParticipants = 50,
                            Participants = 12,
                            Price = "Free",
                            Tags = new List<string>(),
                            Time = new TimeSpan(0, 9, 0, 0, 0),
                            Title = "ICT for Development Workshop 2025",
                            Type = "Workshop"
                        },
                        new
                        {
                            Id = 2,
                            Agenda = new List<string>(),
                            Date = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understanding data protection regulations and best practices for African civil society organisations handling sensitive community data.",
                            Duration = "2 Hours",
                            Format = "Online",
                            Instructor = "Dr. Naledi Khumalo",
                            Level = "Intermediate",
                            Location = "Online (Zoom)",
                            Materials = new List<string>(),
                            MaxParticipants = 100,
                            Participants = 8,
                            Price = "Free",
                            Tags = new List<string>(),
                            Time = new TimeSpan(0, 14, 0, 0, 0),
                            Title = "Data Privacy in African Civil Society",
                            Type = "Webinar"
                        });
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ForumCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3B82F6",
                            Description = "Open discussions about ICT in civil society",
                            Name = "General Discussion"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#10B981",
                            Description = "Questions and help with courses and modules",
                            Name = "Training Support"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#F59E0B",
                            Description = "Share and learn organisational best practices",
                            Name = "Best Practices"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#8B5CF6",
                            Description = "Discuss upcoming events and networking opportunities",
                            Name = "Events & Networking"
                        });
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.ForumReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("ForumReplies");
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.ForumTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorOrg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<int>("Replies")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ForumTopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Admin User",
                            AuthorOrg = "Ungana-Afrika",
                            AuthorRole = "Admin",
                            CategoryId = 1,
                            Content = "Welcome to the UnganaConnect community forum. This is a space for African CSOs to share knowledge, ask questions, and collaborate. Feel free to introduce yourself and your organisation!",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Welcome to the UnganaConnect community forum.",
                            IsAnswered = false,
                            IsPinned = true,
                            Replies = 0,
                            Tags = "welcome,community",
                            Title = "Welcome to UnganaConnect Forum!",
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Demo Member",
                            AuthorOrg = "African Digital Initiative",
                            AuthorRole = "Member",
                            CategoryId = 2,
                            Content = "I just finished the Digital Literacy course and wanted to share some tips that helped me. First, take the quizzes after each module rather than waiting until the end. Second, the resource library has great supplementary materials.",
                            CreatedAt = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Tips and advice for completing the Digital Literacy course.",
                            IsAnswered = false,
                            IsPinned = false,
                            Replies = 0,
                            Tags = "digital-literacy,tips,courses",
                            Title = "Tips for completing the Digital Literacy course",
                            Views = 0
                        });
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Downloads")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("UnganaConnect.Models.Blog.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowComments")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FeaturedImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowComments = true,
                            AuthorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Category = "Technology",
                            Content = "Digital transformation is no longer optional for civil society organisations in Africa. As communities increasingly rely on digital services, CSOs must adapt to remain effective advocates and service providers.\n\nUnganaConnect was built to bridge this gap, providing accessible training, resource sharing, and community engagement tools specifically designed for African civil society.\n\nKey areas where digital tools make the biggest impact include donor reporting, community outreach, internal collaboration, and impact measurement.",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "How digital tools are reshaping the way African civil society organisations operate and deliver impact.",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Tags = "digital-transformation,CSOs,Africa",
                            Title = "Empowering African CSOs Through Digital Transformation",
                            UpdatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Views = 45
                        },
                        new
                        {
                            Id = 2,
                            AllowComments = true,
                            AuthorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Category = "Resources",
                            Content = "Running a non-profit with limited resources does not mean you have to sacrifice productivity. Here are five free tools that can transform how your organisation operates:\n\n1. Google Workspace for Nonprofits - email, docs, and cloud storage\n2. Canva - professional design without a designer\n3. Trello - project management and task tracking\n4. Mailchimp - email marketing for up to 500 contacts\n5. UnganaConnect - training and capacity building for African CSOs",
                            CreatedAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Essential free digital tools that can help non-profits work smarter with limited budgets.",
                            IsFeatured = false,
                            PublishedAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Tags = "tools,NGO,productivity,free",
                            Title = "5 Free Tools Every NGO Should Be Using",
                            UpdatedAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Views = 28
                        });
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Enrolled")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThumbnailContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbnailFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Digital Skills",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A foundational course covering essential digital skills for civil society organisations, including internet safety, email communication, and basic productivity tools.",
                            Duration = "4 weeks",
                            Enrolled = 24,
                            Level = "Beginner",
                            Progress = 0,
                            Rating = 4.5,
                            Status = "available",
                            ThumbnailContentType = "",
                            ThumbnailFileName = "",
                            ThumbnailUrl = "",
                            Title = "Introduction to Digital Literacy"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Data & Analytics",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn how to collect, store, and analyse data effectively. Covers spreadsheets, databases, and reporting tools tailored for non-profit organisations.",
                            Duration = "6 weeks",
                            Enrolled = 18,
                            Level = "Intermediate",
                            Progress = 0,
                            Rating = 4.2000000000000002,
                            Status = "available",
                            ThumbnailContentType = "",
                            ThumbnailFileName = "",
                            ThumbnailUrl = "",
                            Title = "Data Management for NGOs"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Capacity Building",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master the art of writing compelling grant proposals. Includes templates, case studies, and peer review exercises for African CSOs.",
                            Duration = "3 weeks",
                            Enrolled = 32,
                            Level = "Intermediate",
                            Progress = 0,
                            Rating = 4.7999999999999998,
                            Status = "available",
                            ThumbnailContentType = "",
                            ThumbnailFileName = "",
                            ThumbnailUrl = "",
                            Title = "Grant Writing and Proposal Development"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protect your organisation from digital threats. Covers password management, phishing awareness, secure communication, and data privacy compliance.",
                            Duration = "2 weeks",
                            Enrolled = 15,
                            Level = "Beginner",
                            Progress = 0,
                            Rating = 4.5999999999999996,
                            Status = "available",
                            ThumbnailContentType = "",
                            ThumbnailFileName = "",
                            ThumbnailUrl = "",
                            Title = "Cybersecurity Essentials for CSOs"
                        });
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.CourseEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VideoFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("VideoFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.QuizOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizOptions");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("UnganaConnect.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Bio = "Platform administrator for UnganaConnect.",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@unganaconnect.org",
                            FirstName = "Admin",
                            LastName = "User",
                            Location = "Johannesburg, South Africa",
                            Organization = "Ungana-Afrika",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Bio = "A sample CSO member exploring training opportunities.",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "member@unganaconnect.org",
                            FirstName = "Demo",
                            LastName = "Member",
                            Location = "Cape Town, South Africa",
                            Organization = "African Digital Initiative",
                            PasswordHash = "q+LT7VQZ4aIpPANKazdaYi/1pg5aww8pxGEiCJj/3Zc=",
                            Role = "Member",
                            UpdatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.EventRegistration", b =>
                {
                    b.HasOne("UnganaConnect.Frontend.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.ForumReply", b =>
                {
                    b.HasOne("UnganaConnect.Frontend.Models.ForumTopic", "Topic")
                        .WithMany("RepliesList")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.ForumTopic", b =>
                {
                    b.HasOne("UnganaConnect.Frontend.Models.ForumCategory", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UnganaConnect.Models.Blog.BlogPost", b =>
                {
                    b.HasOne("UnganaConnect.Models.User.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.CourseEnrollment", b =>
                {
                    b.HasOne("UnganaConnect.Models.Course.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnganaConnect.Models.User.User", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Module", b =>
                {
                    b.HasOne("UnganaConnect.Models.Course.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnganaConnect.Models.User.User", null)
                        .WithMany("Modules")
                        .HasForeignKey("UserId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Quiz", b =>
                {
                    b.HasOne("UnganaConnect.Models.Course.Module", "Module")
                        .WithMany("Quizzes")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.QuizAttempt", b =>
                {
                    b.HasOne("UnganaConnect.Models.Course.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.QuizOption", b =>
                {
                    b.HasOne("UnganaConnect.Models.Course.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.QuizQuestion", b =>
                {
                    b.HasOne("UnganaConnect.Models.Course.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.ForumCategory", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("UnganaConnect.Frontend.Models.ForumTopic", b =>
                {
                    b.Navigation("RepliesList");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Module", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("UnganaConnect.Models.Course.QuizQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("UnganaConnect.Models.User.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
